### ISSUE TITLE
Modify Wings (with docker) to access  `sudo su`

### ISSUE THREAD

**Issue by leadvic** [ysdragon/Pterodactyl-VPS-Egg#10]
Hey there, thank you for  this repository, I really like it. I'd love to enable `sudo su`, but I'm using wings with docker, so I'm not really sure how to modify the line that you indicate to enable  `sudo su`.

Please let me know what you think about it.

**Comment by ysdragon** [comment]
Hi, for now it's not working, i have said that i will fix it when i have time in the other issue #7
