### ISSUE TITLE
Followed Every Step. Throwing this error

### ISSUE THREAD

**Issue by WispySuccs** [ysdragon/Pterodactyl-VPS-Egg#11]
● wings.service - Pterodactyl Wings Daemon
     Loaded: loaded (/etc/systemd/system/wings.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2023-12-05 10:14:51 CST; 4s ago
    Process: 10543 ExecStart=/usr/local/bin/wings (code=exited, status=203/EXEC)
   Main PID: 10543 (code=exited, status=203/EXEC)
        CPU: 1ms

**Comment by ysdragon** [comment]
Did you tried the built artifact before you move?
`./wings`

**Comment by WispySuccs** [comment]
it says this when i tried that
mv: cannot overwrite non-directory '/usr/local/bin/wings' with directory 'wings'

**Comment by WispySuccs** [comment]
I figured it out. When I did go build. it put the wings exe into something else. please note that down so people like me don't get confused.

**Comment by WispySuccs** [comment]
![image](https://github.com/ysdragon/Pterodactyl-VPS-Egg/assets/75127085/8bf2a93c-e113-4275-9935-864d3adbd33e)
Its saying I don't have sudo after the steps I followed.

**Comment by ysdragon** [comment]
@WispySuccs I have observed in the  [README](https://github.com/ysdragon/Pterodactyl-VPS-Egg/blob/main/README.md) that the "sudo su" option is currently not functioning.
