### ISSUE TITLE
How can I run a service after reboot?

### ISSUE THREAD

**Issue by joti-prime** [ysdragon/Pterodactyl-VPS-Egg#12]
For example, I am using Ubuntu and have installed Nginx. However, after rebooting, I need to manually enable it again using the Nginx command. Is there any way to configure it to start automatically? Any suggestions?

**Comment by ysdragon** [comment]
Try to add your command to start service to:
```bash
~/.bashrc
```

**Comment by MaGnA997** [comment]
```sh 
/home/container/.bashrc
```

**Comment by ysdragon** [comment]
```sh
/home/container/.bashrc
```

**Comment by ysdragon** [comment]
I will create a script to make it simple for everyone. Please use `Void Linux` for now, which autostarts nginx by default.

**Comment by ysdragon** [comment]
Yes, you can create an script and customize it as you want, i will create one soon!
