### ISSUE TITLE
I want ssh to be added from the beginning

### ISSUE THREAD

**Issue by shunya725** [ysdragon/Pterodactyl-VPS-Egg#14]
It is a hassle to install ssh one by one, so please add it from the beginning.

**Comment by ysdragon** [comment]
Sorry, but what's the hassle in installing OpenSSH with just one or two commands?

**Comment by shunya725** [comment]
The assigned port is not port 22, so it is necessary to change it, which is very troublesome.

**Comment by ysdragon** [comment]
You can modify the egg to suit your requirements.
