### ISSUE TITLE
add ssh

### ISSUE THREAD

**Issue by japlic** [ysdragon/Pterodactyl-VPS-Egg#16]
can u add ssh

**Comment by ysdragon** [comment]
Maybe I will add it by default in the future, but there's no ETA because I have no free time at the moment.

**Comment by DevSimpler** [comment]
can u add it rq and fix errors when u say do u wish to contume y/n when add yes it crashes

**Comment by ysdragon** [comment]
Closed because it's not planned, you can install openssh-server by yourself.
