### ISSUE TITLE
Add systemd

### ISSUE THREAD

**Issue by vuthanhtrung2010** [ysdragon/Pterodactyl-VPS-Egg#18]
user@MyVPS:# sudo systemctl enable --now code-server@$USER
sudo: unable to resolve host 0380699e-b6e0-4b90-8d61-d98025a5d60f: Name or service not known
sudo: unable to send audit message: Operation not permitted
Created symlink /etc/systemd/system/default.target.wants/code-server@container.service → /lib/systemd/system/code-server@.service.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
root@MyVPS:#

**Comment by ysdragon** [comment]
You can start it by running:
`service code-server start` for example!
