### ISSUE TITLE
multi port use 

### ISSUE THREAD

**Issue by vincyxiroff** [ysdragon/Pterodactyl-VPS-Egg#21]
like if i have 5 port i can use all of em

**Comment by ysdragon** [comment]
Yes, i will add this feature when i have free time.

**Comment by ChandlerAx** [comment]
Nice egg, very cool & usefull

**Comment by ysdragon** [comment]
@vincyxiroff I have added this feature you can check here: [201881f](https://github.com/ysdragon/Pterodactyl-VPS-Egg/commit/201881f58ffe7d97a47fda85f05862fc9d6b8936)
