### ISSUE TITLE
installer issue

### ISSUE THREAD

**Issue by Popx1** [ysdragon/Pterodactyl-VPS-Egg#24]
\033[0;32m╭────────────────────────────────────────────────────────────────────────────────╮\033[0m
\033[0;32m│                                                                                │\033[0m
\033[0;32m│                             Pterodactyl VPS EGG                                │\033[0m
\033[0;32m│                                                                                │\033[0m
\033[0;32m│                           \033[0;31m© 2021 - 2024 \033[0;35mysdragon\033[0;32m                               │\033[0m
\033[0;32m│                                                                                │\033[0m
\033[0;32m╰────────────────────────────────────────────────────────────────────────────────╯\033[0m
                                                                                               
\033[0;33mPlease choose your favorite distro                                               \033[0m
                                                                                               
* [1] Debian                                                                                   
* [2] Ubuntu                                                                                   
* [3] Void Linux                                                                               
* [4] Alpine Linux  (Edge)                                                                     
* [5] CentOS                                                                                   
* [6] Rocky Linux                                                                              
* [7] Fedora                                                                                   
* [8] AlmaLinux                                                                                
* [9] Slackware Linux                                                                          
* [10] Kali Linux                                                                              
* [11] openSUSE                                                                                
* [12] Gentoo Linux                                                                            
* [13] Arch Linux                                                                              
* [14] Devuan Linux                                                                            
                                                                                               
\033[0;33mEnter OS (1-14):                                                                 \033[0m
2
* [1] Ubuntu 24.04 LTS (noble)
* [2] Ubuntu 22.04 LTS (jammy)
* [3] Ubuntu 20.04 LTS (focal)
* [4] Ubuntu 18.04 LTS (bionic)
* [5] Ubuntu 16.04 LTS (xenial)
\033[0;33mEnter the desired version (1-5): 
1
\033[0;32mInstalling Ubuntu 24.04 LTS (noble)...\033[0m
PteroVM.sh: line 146: curl: not found
grep: unrecognized option: P
BusyBox v1.36.1 (2023-11-07 18:53:09 UTC) multi-call binary.
Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A|B|C N] { PATTERN | -e PATTERN... | -f FILE... } [FILE]...
Search for PATTERN in FILEs (or stdin)
        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -R      Recurse and dereference symlinks
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
PteroVM.sh: line 148: curl: not found
tar: can't open '//rootfs.tar.xz': No such file or directory
PteroVM.sh: line 370: curl: not found
PteroVM.sh: line 378: curl: not found
chmod: //usr/local/bin/proot: No such file or directory
PteroVM.sh: line 386: can't create //etc/resolv.conf: Read-only file system
touch: //.installed: Read-only file system
PteroVM.sh: line 399: can't open //vps.config: no such file
PteroVM.sh: line 409: //usr/local/bin/proot: not found
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 127
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by ysdragon** [comment]
Installer is not supported in alpine/busybox docker image, you can modify it to fit busybox grep.
