### ISSUE TITLE
cant install docker

### ISSUE THREAD

**Issue by JustablockCode** [ysdragon/Pterodactyl-VPS-Egg#29]
Uhh... I'm new to this stuff but, I can't install Docker! And also many other apps. It gives me an error like: `System has not been booted with systemd as init system (PID 1). Can't operate.` ! What can I do to stop this error?

**Comment by ysdragon** [comment]
Sorry? you want to install docker inside a docker container? this is not possible!!

**Comment by JustablockCode** [comment]
oh

tir. 18. juni 2024 kl. 08:08 skrev DraGoN ***@***.***>:
