### ISSUE TITLE
I need information

### ISSUE THREAD

**Issue by ismamilahi** [ysdragon/Pterodactyl-VPS-Egg#30]
Hello dear developer, 
i need information about vps is can i able to install pterodactyl wings in "Pterodactyl-VPS-Egg" ??
and i able to install than how to install can you help me please!

**Comment by MasonDye** [comment]
you can't do this, because docker does not allow nested virtualization

**Comment by ysdragon** [comment]
> Hello dear developer, i need information about vps is can i able to install pterodactyl wings in "Pterodactyl-VPS-Egg" ?? and i able to install than how to install can you help me please!

No, you can't.
It's impossible to install pterodactyl wings inside a docker container!!!!!!!
