### ISSUE TITLE
Nano error

### ISSUE THREAD

**Issue by Higor-US** [ysdragon/Pterodactyl-VPS-Egg#41]
Hello, I try to use the command but apparently it runs but does not appear in the terminal, but when I do a stop event in the container it appears, I don't know if it could be an error on my part or an error in the egg itself!

Thank you for your dedication to the script, I'm looking forward to new phases of it! (: 

See image below:

![image](https://github.com/user-attachments/assets/1918bac4-514e-4c1a-887b-221709eafe71)

**Comment by ysdragon** [comment]
You shouldn't use nano within the Pterodactyl server console since it's not a full-featured terminal console and is usually used just to monitor the server! However, you can use it when you run a browser terminal like Getty or something similar, such as an Ngrok-tunneled SSH server.
