### ISSUE TITLE
config file not generating for ssh

### ISSUE THREAD

**Issue by errcruze** [ysdragon/Pterodactyl-VPS-Egg#43]
user@MyVPS:~# 
user@MyVPS:~# install-ssh
[INFO] Installing wget.
/usr/bin/wget
[INFO] Installing SSH.
[INFO] SSH installed successfully.
user@MyVPS:~# 
user@MyVPS:~# cat /.ssh_config
cat: /.ssh_config: No such file or directory
user@MyVPS:~#

**Comment by ysdragon** [comment]
What's the distro image that you have installed?

**Comment by ysdragon** [comment]
Please create it like this:
https://github.com/ysdragon/Pterodactyl-VPS-Egg?tab=readme-ov-file#example-ssh_config-configuration
