### ISSUE TITLE
Ubuntu "focal" not starting

### ISSUE THREAD

**Issue by TuPiDAn9** [ysdragon/Pterodactyl-VPS-Egg#44]
/run.sh: 47: local: 'help': bad variable name
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by MasonDye** [comment]
I encountered this bug.

**Comment by ysdragon** [comment]
Fixed now.
@TuPiDAn9 @MasonDye Thanks for reporting.
