### ISSUE TITLE
Arm Processor Support ETA? 

### ISSUE THREAD

**Issue by SavageTheUnicorn** [ysdragon/Pterodactyl-VPS-Egg#5]
I noticed from the closed issues that there was talk of arm cpus not being supported. Is there a chance this has been worked on since July and if so, could there be an ETA? Or is this a feature that will not be planned?

**Comment by ysdragon** [comment]
Could you attempt to locally build the Docker image on an ARM-based CPU and then incorporate it into the Pterodactyl image by editing the egg Docker Images field?

**Comment by ysdragon** [comment]
Closed due to no response.

**Comment by SavageTheUnicorn** [comment]
Apologies I don't get notifications from github and my email notifications are spotty. I can attempt this in the next 2-3 days possibly. I'm getting a new pc so I'll be a bit busy with that and work.

**Comment by ysdragon** [comment]
Okay, no problem.

**Comment by SavageTheUnicorn** [comment]
I can transfer the dockerfile and build it but I have no idea how to use the image. I get the sha256 of it but that's about all

**Comment by ysdragon** [comment]
You can build it with a specific name, and then attempt to modify the egg Docker images field by using your local Docker image. Then navigate to the 'Install Script > Script Container' field and edit it with your local Docker image.

**Comment by ysdragon** [comment]
Please check now
