### ISSUE TITLE
How to Build Pterodactyl Wings.

### ISSUE THREAD

**Issue by fuzeblocks** [ysdragon/Pterodactyl-VPS-Egg#6]
HI 👋 , I need your help for Build Pterodactyl Wings because i can't lunch the file

**Comment by ysdragon** [comment]
Install golang, then remove the following [line](https://github.com/pterodactyl/wings/blob/48c55af373684847c7f61035c0038c5e470e286c/environment/docker/container.go#L250) from wings source code
Then run 
```sh
go build
```
