### ISSUE TITLE
Issue After All Steps

### ISSUE THREAD

**Issue by Leourel** [ysdragon/Pterodactyl-VPS-Egg#7]
Did All the steps and encountered this Issue when trying to do sudo apt update

user@MyVPS:~ sudo apt update
sudo: you do not exist in the passwd database

Please Help, Thanks!

**Comment by BasToTheMax** [comment]
What happens when not using sudo?

**Comment by ysdragon** [comment]
> Did All the steps and encountered this Issue when trying to do sudo apt update
> 
> user@MyVPS:~ sudo apt update sudo: you do not exist in the passwd database
> 
> Please Help, Thanks!

I'll fix it, thx.

**Comment by ysdragon** [comment]
closed as we added inital root and multi os support, see [#d341f98](https://github.com/ysdragon/Pterodactyl-VPS-Egg/commit/d341f9888be0a99453e2cad42c01cb2f3bb79334)
