### ISSUE TITLE
su - It requires a passwd??

### ISSUE THREAD

**Issue by YuaVN** [ysdragon/Pterodactyl-VPS-Egg#9]
started
user@MyVPS:~ su
Password: 
su: Authentication failure
user@MyVPS:~ 
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Server crash was detected but an error occurred while handling it.
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...

It requires a passwd??? WTF, what is the password? Did I set it up incorrectly somewhere?

**Comment by ysdragon** [comment]
This is a dublicated issue, this is a bug you can see the previous #7

**Comment by YuaVN** [comment]
> This is a dublicated issue, this is a bug you can see the previous #7

When you fix it?

**Comment by ysdragon** [comment]
> > This is a dublicated issue, this is a bug you can see the previous #7
> 
> When you fix it?

When i have time in the near future.

**Comment by YuaVN** [comment]
> > > This is a dublicated issue, this is a bug you can see the previous #7
> > 
> > 
> > When you fix it?
> 
> When i have time in the near future.

Is there any other way for me to access root? I need it

**Comment by ysdragon** [comment]
> > > > This is a dublicated issue, this is a bug you can see the previous #7
> > > 
> > > 
> > > When you fix it?
> > 
> > 
> > When i have time in the near future.
> 
> Is there any other way for me to access root? I need it

No, for now you can rebuild the docker image with your needs and add it to pterodactyl.
